on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-node@v4
      with:
        node-version: 20

    - run: npm i -g yarn && yarn install --frozen-lockfile && npm run docs

    - uses: actions/upload-artifact@v4
      with:
        # Name of the artifact to upload.
        # Optional. Default is 'artifact'
        name: AJSDocs

        # A file, directory or wildcard pattern that describes what to upload
        # Required.
        path: bin